description: gendata

environment:
  image: amlt-sing/acpt-torch2.4.1-py3.10-cuda12.4-ubuntu22.04

  setup:
    - git clone https://github.com/zhangmiaosen2000/cccrawl.git
    - cd cccrawl
    - bash install.sh
storage:
  lmm:
    container_name: vground
    mount_dir: /mnt/vground
    storage_account_name: t2vgusw2
    is_output: True


target:
  workspace_name: t2vgws2
  service: sing
  name: msrresrchvc

jobs:

  - name: split_0_0to1
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          
    sla_tier: premium   
    identity: managed
    
    sku: 10C3
    command:
      - cd cccrawl
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_0to1 --start 0 --end 1

  - name: split_0_1to2
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          
    sla_tier: premium   
    identity: managed
    
    sku: 10C3
    command:
      - cd cccrawl
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_1to2 --start 1 --end 2

  - name: split_0_2to3
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          
    sla_tier: premium   
    identity: managed
    
    sku: 10C3
    command:
      - cd cccrawl
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_2to3 --start 2 --end 3

  - name: split_0_3to4
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          
    sla_tier: premium   
    identity: managed
    
    sku: 10C3
    command:
      - cd cccrawl
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_3to4 --start 3 --end 4
