description: gendata

env_defaults:
  GPU_NUM: 1
  SKU: G1
  TARGET: msrresrchlab
  SLA: premium

environment:
  image: amlt-sing/acpt-torch2.4.1-py3.10-cuda12.4-ubuntu22.04

  setup:
    - bash install.sh
storage:
  lmm:
    container_name: vground
    mount_dir: /mnt/vground
    storage_account_name: t2vgusw2
    is_output: True


target:
  workspace_name: t2vgws2
  service: sing
  name: ${TARGET}

jobs:
  - name: split_0_0to1
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          # [High, Medium, Low]. On AMLK8s, the priority value is mapped to 200, 100, and 80, respectively.
    sla_tier: ${SLA}       # [premium, standard, basic]
    identity: managed
    
    sku: ${SKU}
    command:
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_0to1 --start 0 --end 1
  
  - name: split_0_1to2
    process_count_per_node: 1
    execution_mode: Basic
    priority: High          # [High, Medium, Low]. On AMLK8s, the priority value is mapped to 200, 100, and 80, respectively.
    sla_tier: ${SLA}       # [premium, standard, basic]
    identity: managed
    
    sku: ${SKU}
    command:
      - python gendata_main.py --index /mnt/vground/selected_url_from_domain/CCurls_sampled_50pd_split_0.json --out-dir /mnt/vground/CCCrawl_Raw --run-name split_0_1to2 --start 1 --end 2
  